/**
 ******************************************************************************
 * @file      startup_stm32wl55jcix.s
 * @author    Auto-generated by STM32CubeIDE
 * @brief     STM32WL55JCIx device vector table for GCC toolchain.
 *            This module performs:
 *                - Set the initial SP
 *                - Set the initial PC == Reset_Handler,
 *                - Set the vector table entries with the exceptions ISR address
 *                - Branches to main in the C library (which eventually
 *                  calls main()).
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

.syntax unified
.cpu cortex-m0plus
.fpu softvfp
.thumb

.global g_pfnVectors
.global Default_Handler

/* start address for the initialization values of the .data section.
defined in linker script */
.word _sidata
/* start address for the .data section. defined in linker script */
.word _sdata
/* end address for the .data section. defined in linker script */
.word _edata
/* start address for the .bss section. defined in linker script */
.word _sbss
/* end address for the .bss section. defined in linker script */
.word _ebss

/**
 * @brief  This is the code that gets called when the processor first
 *          starts execution following a reset event. Only the absolutely
 *          necessary set is performed, after which the application
 *          supplied main() routine is called.
 * @param  None
 * @retval : None
*/

  .section .text.Reset_Handler
  .weak Reset_Handler
  .type Reset_Handler, %function
Reset_Handler:
  ldr   r0, =_estack
  mov   sp, r0          /* set stack pointer */
/* Call the clock system initialization function.*/
  bl  SystemInit

/* Copy the data segment initializers from flash to SRAM */
  ldr r0, =_sdata
  ldr r1, =_edata
  ldr r2, =_sidata
  movs r3, #0
  b LoopCopyDataInit

CopyDataInit:
  ldr r4, [r2, r3]
  str r4, [r0, r3]
  adds r3, r3, #4

LoopCopyDataInit:
  adds r4, r0, r3
  cmp r4, r1
  bcc CopyDataInit

/* Zero fill the bss segment. */
  ldr r2, =_sbss
  ldr r4, =_ebss
  movs r3, #0
  b LoopFillZerobss

FillZerobss:
  str  r3, [r2]
  adds r2, r2, #4

LoopFillZerobss:
  cmp r2, r4
  bcc FillZerobss


/* Call static constructors */
  bl __libc_init_array
/* Call the application's entry point.*/

  bl main

LoopForever:
  b LoopForever

  .size Reset_Handler, .-Reset_Handler

/**
 * @brief  This is the code that gets called when the processor receives an
 *         unexpected interrupt.  This simply enters an infinite loop, preserving
 *         the system state for examination by a debugger.
 *
 * @param  None
 * @retval : None
*/
  .section .text.Default_Handler,"ax",%progbits
Default_Handler:
Infinite_Loop:
  b Infinite_Loop
  .size Default_Handler, .-Default_Handler

/******************************************************************************
*
* The STM32WL55JCIx vector table.  Note that the proper constructs
* must be placed on this to ensure that it ends up at physical address
* 0x0000.0000.
*
******************************************************************************/


  .section .isr_vector,"a",%progbits
  .type g_pfnVectors, %object

g_pfnVectors:
  .word _estack
  .word Reset_Handler
  .word NMI_Handler
  .word HardFault_Handler
  .word	0
  .word	0
  .word	0
  .word	0
  .word	0
  .word	0
  .word	0
  .word	SVC_Handler
  .word	0
  .word	0
  .word	PendSV_Handler
  .word	SysTick_Handler
  .word	TZIC_ILA_IRQHandler                                     			/* Security Interrupt controller illegal access interrupt                                                               */
  .word	PVD_PVM_3_IRQHandler                                    			/* PVD through EXTI[16], PVM[3] through EXTI[34]                                                                        */
  .word	TAMP_RTCSTAMP_LSECSS_RTCALARM_RTCSSRU_RTCWKUP_IRQHandler			/* Tamper, TimeStamp, LSECSS,alarm A and B,SSR underflow,RTC wakeup interrupt                                           */
  .word	FLASH_RCC_C1SEV_IRQHandler                              			/* Flash memory global interrupt and Flash memory ECC single error interrupt,RCC global interrupt,CPU1 SEV through EXTI */
  .word	EXTI1_0_IRQHandler                                      			/* EXTI line 0 interrupt through EXTI                                                                                   */
  .word	EXTI3_2_IRQHandler                                      			/* EXTI line 1 interrupt through EXTI                                                                                   */
  .word	EXTI15_4_IRQHandler                                     			/* EXTI line 2 interrupt through EXTI                                                                                   */
  .word	ADC_COMP_DAC_IRQHandler                                 			/* ADC and DAC global interrupt,COMP1 and COMP2 interrupt through EXTI                                                  */
  .word	DMA1_CH3_1_IRQHandler                                   			/* DMA1 channel 3:1 secure and non-secure interrupt (C2IMR2[2:0])                                                       */
  .word	DMA1_CH7_4_IRQHandler                                   			/* DMA1 channel 7:4 secure and non-secure interrupt (C2IMR2[6:3])                                                       */
  .word	DMA2_CH7_1_DMAMUX1_OVR_IRQHandler                       			/* DMA2 channel 7:1 secure and non-secure interrupt (C2IMR2[14:8]),DMAMUX1 overrun interrupt (C2IMR2[15])               */
  .word	LPTIM1_IRQHandler                                       			/* LPtimer 1 global interrupt                                                                                           */
  .word	LPTIM2_IRQHandler                                       			/* LPtimer 2 global interrupt                                                                                           */
  .word	LPTIM3_IRQHandler                                       			/* LPtimer 3 global interrupt                                                                                           */
  .word	TIM1_BRK_TIM1_UP_TIM1_TRG_COM_TIM1_CC_IRQHandler        			/* Timer 1 break, update, trigger and communication,capture compare interrupt                                           */
  .word	TIM2_IRQHandler                                         			/* Timer 2 global interrupt                                                                                             */
  .word	TIM16_IRQHandler                                        			/* Timer 16 global interrupt                                                                                            */
  .word	TIM17_IRQHandler                                        			/* Timer 17 global interrupt                                                                                            */
  .word	IPCC_C2_RX_IT_IPCC_C2_TX_IT_IRQHandler                  			/* IPCC CPU2 RX occupied interrupt, IPCC CPU2 TX free interrupt                                                         */
  .word	HSEM_IRQHandler                                         			/* Semaphore interrupt 1 to CPU2                                                                                        */
  .word	True_RNG_IRQHandler                                     			/* True random number generator interrupt                                                                               */
  .word	AES_PKA_IRQHandler                                      			/* AES global interrupt , Private key accelerator interrupt                                                             */
  .word	I2C1_EV_I2C1_ER_IRQHandler                              			/* I2C1 event interrupt,I2C1 error interrupt                                                                            */
  .word	I2C2_EV_I2C2_ER_IRQHandler                              			/* I2C2 event interrupt , I2C2 error interrupt                                                                          */
  .word	I2C3_EV_I2C3_ER_IRQHandler                              			/* I2C3 event interrupt , I2C2 error interrupt                                                                          */
  .word	SPI1_IRQHandler                                         			/* SPI 1 global interrupt                                                                                               */
  .word	SPI2S2_IRQHandler                                       			/* SPI2S2 global interrupt                                                                                              */
  .word	USART1_IRQHandler                                       			/* USART1 global interrupt                                                                                              */
  .word	USART2_IRQHandler                                       			/* USART2 global interrupt                                                                                              */
  .word	LPUART1_IRQHandler                                      			/* LPUART1 global interrupt                                                                                             */
  .word	SUBGHZSPI_IRQHandler                                    			/* Sub-GHz radio SPI global interrupt                                                                                   */
  .word	Radio_IRQ_Busy_IRQHandler                               			/* Radio IRQs, RFBUSY interrupt through EXTI                                                                            */
  .size g_pfnVectors, .-g_pfnVectors

/*******************************************************************************
*
* Provide weak aliases for each Exception handler to the Default_Handler.
* As they are weak aliases, any function with the same name will override
* this definition.
*
*******************************************************************************/

	.weak	NMI_Handler
	.thumb_set NMI_Handler,Default_Handler

	.weak	HardFault_Handler
	.thumb_set HardFault_Handler,Default_Handler

	.weak	SVC_Handler
	.thumb_set SVC_Handler,Default_Handler

	.weak	PendSV_Handler
	.thumb_set PendSV_Handler,Default_Handler

	.weak	SysTick_Handler
	.thumb_set SysTick_Handler,Default_Handler

	.weak	TZIC_ILA_IRQHandler
	.thumb_set TZIC_ILA_IRQHandler,Default_Handler

	.weak	PVD_PVM_3_IRQHandler
	.thumb_set PVD_PVM_3_IRQHandler,Default_Handler

	.weak	TAMP_RTCSTAMP_LSECSS_RTCALARM_RTCSSRU_RTCWKUP_IRQHandler
	.thumb_set TAMP_RTCSTAMP_LSECSS_RTCALARM_RTCSSRU_RTCWKUP_IRQHandler,Default_Handler

	.weak	FLASH_RCC_C1SEV_IRQHandler
	.thumb_set FLASH_RCC_C1SEV_IRQHandler,Default_Handler

	.weak	EXTI1_0_IRQHandler
	.thumb_set EXTI1_0_IRQHandler,Default_Handler

	.weak	EXTI3_2_IRQHandler
	.thumb_set EXTI3_2_IRQHandler,Default_Handler

	.weak	EXTI15_4_IRQHandler
	.thumb_set EXTI15_4_IRQHandler,Default_Handler

	.weak	ADC_COMP_DAC_IRQHandler
	.thumb_set ADC_COMP_DAC_IRQHandler,Default_Handler

	.weak	DMA1_CH3_1_IRQHandler
	.thumb_set DMA1_CH3_1_IRQHandler,Default_Handler

	.weak	DMA1_CH7_4_IRQHandler
	.thumb_set DMA1_CH7_4_IRQHandler,Default_Handler

	.weak	DMA2_CH7_1_DMAMUX1_OVR_IRQHandler
	.thumb_set DMA2_CH7_1_DMAMUX1_OVR_IRQHandler,Default_Handler

	.weak	LPTIM1_IRQHandler
	.thumb_set LPTIM1_IRQHandler,Default_Handler

	.weak	LPTIM2_IRQHandler
	.thumb_set LPTIM2_IRQHandler,Default_Handler

	.weak	LPTIM3_IRQHandler
	.thumb_set LPTIM3_IRQHandler,Default_Handler

	.weak	TIM1_BRK_TIM1_UP_TIM1_TRG_COM_TIM1_CC_IRQHandler
	.thumb_set TIM1_BRK_TIM1_UP_TIM1_TRG_COM_TIM1_CC_IRQHandler,Default_Handler

	.weak	TIM2_IRQHandler
	.thumb_set TIM2_IRQHandler,Default_Handler

	.weak	TIM16_IRQHandler
	.thumb_set TIM16_IRQHandler,Default_Handler

	.weak	TIM17_IRQHandler
	.thumb_set TIM17_IRQHandler,Default_Handler

	.weak	IPCC_C2_RX_IT_IPCC_C2_TX_IT_IRQHandler
	.thumb_set IPCC_C2_RX_IT_IPCC_C2_TX_IT_IRQHandler,Default_Handler

	.weak	HSEM_IRQHandler
	.thumb_set HSEM_IRQHandler,Default_Handler

	.weak	True_RNG_IRQHandler
	.thumb_set True_RNG_IRQHandler,Default_Handler

	.weak	AES_PKA_IRQHandler
	.thumb_set AES_PKA_IRQHandler,Default_Handler

	.weak	I2C1_EV_I2C1_ER_IRQHandler
	.thumb_set I2C1_EV_I2C1_ER_IRQHandler,Default_Handler

	.weak	I2C2_EV_I2C2_ER_IRQHandler
	.thumb_set I2C2_EV_I2C2_ER_IRQHandler,Default_Handler

	.weak	I2C3_EV_I2C3_ER_IRQHandler
	.thumb_set I2C3_EV_I2C3_ER_IRQHandler,Default_Handler

	.weak	SPI1_IRQHandler
	.thumb_set SPI1_IRQHandler,Default_Handler

	.weak	SPI2S2_IRQHandler
	.thumb_set SPI2S2_IRQHandler,Default_Handler

	.weak	USART1_IRQHandler
	.thumb_set USART1_IRQHandler,Default_Handler

	.weak	USART2_IRQHandler
	.thumb_set USART2_IRQHandler,Default_Handler

	.weak	LPUART1_IRQHandler
	.thumb_set LPUART1_IRQHandler,Default_Handler

	.weak	SUBGHZSPI_IRQHandler
	.thumb_set SUBGHZSPI_IRQHandler,Default_Handler

	.weak	Radio_IRQ_Busy_IRQHandler
	.thumb_set Radio_IRQ_Busy_IRQHandler,Default_Handler

	.weak	SystemInit

/************************ (C) COPYRIGHT STMicroelectronics *****END OF FILE****/
